name: insightos_warehouse
version: "1.0.0"
profile: insightos_warehouse

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: target
clean-targets: [target, dbt_packages]

models:
  insightos_warehouse:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

seeds:
  insightos_warehouse:
    +schema: seeds
