"""Deterministic narrative generation - the layer that makes charts explain themselves.

Every sentence produced here is derived from a computed number and carries the
evidence that produced it. Nothing is generated by a language model. The optional
:mod:`insightos.narrative.polish` adapter may rephrase these sentences, but it is
given the facts as a closed set and its output is verified against them, so an LLM
can never introduce a claim the analytics did not make.

The writers cover the shapes a business chart actually takes:

* ``describe_series``   - trend, inflection, seasonality, latest move, volatility
* ``describe_breakdown``- concentration, leaders, laggards, long tail
* ``describe_comparison``- period-over-period movement with mix attribution
* ``describe_distribution`` - shape, skew, outliers, where the mass sits
* ``describe_correlation``  - strength, direction, and an explicit "not causation"
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import asdict, dataclass, field
from typing import Any

import numpy as np

from ..statistics.tests import pearson_correlation, spearman_correlation
from ..statistics.timeseries import (
    detect_change_points,
    detect_seasonality,
    mann_kendall,
    theil_sen_slope,
)
from ..types import Evidence, to_jsonable

__all__ = ["ChartNarrative", "describe_series", "describe_breakdown",
           "describe_comparison", "describe_distribution", "describe_correlation",
           "format_value"]


@dataclass
class ChartNarrative:
    chart_id: str
    title: str
    headline: str
    bullets: list[str] = field(default_factory=list)
    evidence: list[Evidence] = field(default_factory=list)
    method_notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(asdict(self))


def format_value(value: float | None, unit: str = "number", decimals: int | None = None) -> str:
    """Human formatting that keeps executives reading instead of counting zeros."""
    if value is None or not np.isfinite(value):
        return "n/a"
    v = float(value)
    if unit == "percent":
        return f"{v:,.{1 if decimals is None else decimals}f}%"
    if unit == "ratio":
        return f"{v:,.2f}x"
    if unit == "currency":
        a = abs(v)
        for div, suf in ((1e9, "B"), (1e6, "M"), (1e3, "K")):
            if a >= div:
                return f"${v / div:,.2f}{suf}"
        return f"${v:,.2f}"
    a = abs(v)
    for div, suf in ((1e9, "B"), (1e6, "M"), (1e3, "K")):
        if a >= div:
            return f"{v / div:,.2f}{suf}"
    return f"{v:,.{0 if decimals is None else decimals}f}"


def _pct(a: float | None, b: float | None) -> float | None:
    if a is None or b in (None, 0) or not np.isfinite(a) or not np.isfinite(b):
        return None
    return (a - b) / abs(b) * 100.0


def describe_series(
    chart_id: str,
    title: str,
    values: Sequence[float],
    labels: Sequence[str],
    unit: str = "number",
    metric_label: str = "The metric",
    higher_is_better: bool = True,
    seasonal_period: int | None = None,
) -> ChartNarrative:
    """Explain a time series: where it went, when it turned, and how reliably."""
    pairs = [(labels[i] if i < len(labels) else str(i), float(v))
             for i, v in enumerate(values) if v is not None and np.isfinite(v)]
    if len(pairs) < 3:
        return ChartNarrative(chart_id, title,
                              headline=f"{metric_label} has too few periods to describe.")
    names = [p[0] for p in pairs]
    y = np.array([p[1] for p in pairs])
    bullets: list[str] = []
    evidence: list[Evidence] = []
    notes: list[str] = []

    total_change = _pct(y[-1], y[0])
    trend = mann_kendall(list(y))
    slope = theil_sen_slope(list(y))
    word = {"increasing": "rose", "decreasing": "fell", "no trend": "was broadly flat"}.get(
        trend.direction, "moved")
    if trend.significant:
        headline = (f"{metric_label} {word} {abs(total_change):.1f}% across the "
                    f"{len(y)} periods from {names[0]} to {names[-1]}."
                    if total_change is not None else
                    f"{metric_label} {word} steadily from {names[0]} to {names[-1]}.")
        bullets.append(
            f"The trend is statistically significant (Mann-Kendall tau {trend.tau:+.2f}, "
            f"p = {trend.p_value:.4g}), moving about {format_value(slope, unit)} per period."
        )
        evidence.append(Evidence(
            label=f"{metric_label} is {trend.direction}",
            method="Mann-Kendall trend test with Theil-Sen slope",
            value=round(float(trend.tau), 4), p_value=round(float(trend.p_value), 6),
            sample_size=int(len(y)),
            comparison=f"Theil-Sen slope {slope:,.4f} per period.",
        ))
    else:
        headline = (f"{metric_label} shows no statistically reliable trend across "
                    f"{len(y)} periods; period-to-period movement is noise-dominated.")
        bullets.append(f"Mann-Kendall finds no significant trend (p = {trend.p_value:.3g}), "
                       f"so period-to-period movement should not be read as direction.")
        evidence.append(Evidence(
            label=f"{metric_label} has no significant trend",
            method="Mann-Kendall trend test", value=round(float(trend.tau), 4),
            p_value=round(float(trend.p_value), 6), sample_size=int(len(y)),
        ))

    for cp in detect_change_points(list(y), labels=names, max_points=2):
        verb = "accelerated" if cp.mean_after > cp.mean_before else "slowed"
        bullets.append(
            f"The pattern {verb} after {cp.label or names[cp.index]}: the average moved from "
            f"{format_value(cp.mean_before, unit)} to {format_value(cp.mean_after, unit)} "
            f"({cp.delta_pct:+.1f}%)."
        )
        evidence.append(Evidence(
            label=f"A level change occurred at {cp.label or names[cp.index]}",
            value=round(float(cp.delta_pct), 2),
            method="binary segmentation change point, Welch-validated",
            p_value=round(float(cp.p_value), 6), sample_size=int(len(y)),
            comparison=f"Mean {cp.mean_before:,.2f} -> {cp.mean_after:,.2f}.",
        ))
        notes.append("Change points are validated with a Welch t-test at alpha = 0.01.")

    if seasonal_period or len(y) >= 8:
        seas = (detect_seasonality(list(y), candidate_periods=[seasonal_period])
                if seasonal_period else detect_seasonality(list(y)))
        if seas.detected and seas.period:
            bullets.append(
                f"A repeating {seas.period}-period seasonal cycle is present "
                f"(autocorrelation {seas.strength:.2f}); compare like periods rather than "
                f"consecutive ones."
            )
            evidence.append(Evidence(
                label=f"A {seas.period}-period seasonal cycle exists",
                method="autocorrelation scan over candidate periods",
                value=round(float(seas.strength), 4), sample_size=int(len(y)),
            ))

    if len(y) >= 2:
        last = _pct(y[-1], y[-2])
        if last is not None:
            good = (last >= 0) == higher_is_better
            bullets.append(
                f"The most recent period ({names[-1]}) came in at "
                f"{format_value(y[-1], unit)}, {last:+.1f}% versus {names[-2]} - "
                f"{'a favourable' if good else 'an unfavourable'} move."
            )

    mean = float(np.mean(y))
    cv = (float(np.std(y)) / abs(mean) * 100.0) if mean else 0.0
    if cv > 25:
        bullets.append(f"The series is volatile (coefficient of variation {cv:.0f}%), so "
                       f"single-period swings are weak evidence on their own.")
    peak, trough = int(np.argmax(y)), int(np.argmin(y))
    bullets.append(f"It peaked at {format_value(y[peak], unit)} in {names[peak]} and bottomed "
                   f"at {format_value(y[trough], unit)} in {names[trough]}.")
    return ChartNarrative(chart_id, title, headline, bullets, evidence, notes)


def describe_breakdown(
    chart_id: str,
    title: str,
    segments: Sequence[str],
    values: Sequence[float],
    unit: str = "number",
    dimension: str = "segment",
    metric_label: str = "Value",
) -> ChartNarrative:
    """Explain a categorical breakdown: concentration, leaders and the long tail."""
    pairs = sorted(
        [(str(s), float(v)) for s, v in zip(segments, values)
         if v is not None and np.isfinite(v)],
        key=lambda p: -p[1],
    )
    if not pairs:
        return ChartNarrative(chart_id, title, headline="No data available for this breakdown.")
    total = sum(v for _, v in pairs)
    if total <= 0:
        return ChartNarrative(chart_id, title,
                              headline=f"{metric_label} totals zero across {dimension}.")
    shares = [(s, v, v / total * 100.0) for s, v in pairs]
    top = shares[0]
    bullets: list[str] = []
    evidence: list[Evidence] = []

    headline = (f"{top[0]} leads {dimension} with {format_value(top[1], unit)}, "
                f"{top[2]:.1f}% of the {format_value(total, unit)} total.")

    cum, n_for_80 = 0.0, 0
    for _, _, sh in shares:
        cum += sh
        n_for_80 += 1
        if cum >= 80:
            break
    # Herfindahl-Hirschman index: the standard concentration measure, and the one a
    # risk or regulatory reader will already know how to interpret. It also decides
    # the wording below, so the Pareto sentence can never contradict the HHI verdict.
    hhi = sum((sh / 100.0) ** 2 for _, _, sh in shares) * 10000
    level = ("highly concentrated" if hhi > 2500 else
             "moderately concentrated" if hhi > 1500 else "competitive")
    if len(shares) > 1:
        bullets.append(
            f"{n_for_80} of {len(shares)} {dimension} values account for "
            f"{cum:.0f}% of the total - "
            + ("a concentration risk worth monitoring." if hhi > 2500 else
               "a moderately uneven split." if hhi > 1500 else
               "a broadly balanced distribution.")
        )
    bullets.append(f"By the Herfindahl-Hirschman Index the mix is {level} "
                   f"(HHI {hhi:,.0f} across {len(shares)} {dimension} values; "
                   f"above 2,500 is considered concentrated).")
    evidence.append(Evidence(
        label=f"{dimension} concentration is {level}",
        method="Herfindahl-Hirschman Index over segment shares",
        value=round(float(hhi), 1), sample_size=len(shares),
        comparison=f"Top segment share {top[2]:.1f}%.",
    ))

    if len(shares) >= 3:
        top3 = sum(sh for _, _, sh in shares[:3])
        bullets.append(f"The top three ({', '.join(s for s, _, _ in shares[:3])}) together "
                       f"contribute {top3:.1f}%.")
    tail = [s for s, _, sh in shares if sh < 2.0]
    if len(tail) >= 3:
        tail_share = sum(sh for _, _, sh in shares if sh < 2.0)
        bullets.append(f"A long tail of {len(tail)} {dimension} values contributes only "
                       f"{tail_share:.1f}% combined and can usually be grouped.")
    if len(shares) > 1:
        bottom = shares[-1]
        bullets.append(f"{bottom[0]} is the smallest at {format_value(bottom[1], unit)} "
                       f"({bottom[2]:.1f}%), {top[1] / bottom[1]:,.1f}x below the leader."
                       if bottom[1] else
                       f"{bottom[0]} contributed nothing in this period.")
    return ChartNarrative(chart_id, title, headline, bullets, evidence,
                          ["Shares are computed on the filtered period shown in the chart."])


def describe_comparison(
    chart_id: str,
    title: str,
    segments: Sequence[str],
    current: Sequence[float],
    baseline: Sequence[float],
    unit: str = "number",
    dimension: str = "segment",
    metric_label: str = "Value",
    current_label: str = "current period",
    baseline_label: str = "prior period",
) -> ChartNarrative:
    """Explain a period-over-period comparison and attribute the movement."""
    rows = [(str(s), float(c), float(b))
            for s, c, b in zip(segments, current, baseline)
            if c is not None and b is not None and np.isfinite(c) and np.isfinite(b)]
    if not rows:
        return ChartNarrative(chart_id, title, headline="No comparable data.")
    tc, tb = sum(r[1] for r in rows), sum(r[2] for r in rows)
    total_delta = tc - tb
    total_pct = _pct(tc, tb)
    bullets: list[str] = []
    evidence: list[Evidence] = []

    headline = (
        f"{metric_label} moved from {format_value(tb, unit)} in {baseline_label} to "
        f"{format_value(tc, unit)} in {current_label}"
        + (f", {total_pct:+.1f}%." if total_pct is not None else ".")
    )
    contrib = sorted(
        [(s, c - b, ((c - b) / total_delta * 100.0) if total_delta else None, _pct(c, b))
         for s, c, b in rows],
        key=lambda r: -abs(r[1]),
    )
    drivers = [r for r in contrib if (r[1] > 0) == (total_delta > 0)][:3]
    offsets = [r for r in contrib if (r[1] > 0) != (total_delta > 0)][:2]
    for s, d, share, pct in drivers:
        bullets.append(
            f"{s} drove the change, contributing {format_value(d, unit)}"
            + (f" ({share:.1f}% of the total movement)" if share is not None else "")
            + (f" on a {pct:+.1f}% move." if pct is not None else ".")
        )
        if share is not None:
            evidence.append(Evidence(
                label=f"{s} contributed {share:.1f}% of the {metric_label} change",
                method="additive contribution decomposition",
                value=round(float(share), 2), sample_size=len(rows),
                comparison=f"Delta {d:,.2f} of total {total_delta:,.2f}.",
            ))
    for s, d, share, pct in offsets:
        bullets.append(
            f"{s} moved the other way ({pct:+.1f}%), offsetting "
            f"{format_value(abs(d), unit)} of the change."
        )
    if not drivers:
        bullets.append("No single segment dominated; the movement was spread evenly.")
    return ChartNarrative(chart_id, title, headline, bullets, evidence,
                          ["Contributions are exact for additive measures and indicative "
                           "for ratios, where a mix/rate split is reported separately."])


def describe_distribution(
    chart_id: str,
    title: str,
    values: Sequence[float],
    unit: str = "number",
    metric_label: str = "Values",
) -> ChartNarrative:
    """Explain a distribution: centre, shape, spread and tail risk."""
    x = np.array([float(v) for v in values if v is not None and np.isfinite(v)])
    if x.size < 5:
        return ChartNarrative(chart_id, title, headline="Too few values to describe a shape.")
    mean, med = float(np.mean(x)), float(np.median(x))
    q1, q3 = float(np.percentile(x, 25)), float(np.percentile(x, 75))
    iqr = q3 - q1
    sd = float(np.std(x, ddof=1)) if x.size > 1 else 0.0
    skew = (float(np.mean(((x - mean) / sd) ** 3)) if sd > 0 else 0.0)
    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    out = int(((x < lo) | (x > hi)).sum())
    shape = ("strongly right-skewed" if skew > 1 else "right-skewed" if skew > 0.5 else
             "strongly left-skewed" if skew < -1 else "left-skewed" if skew < -0.5 else
             "approximately symmetric")
    headline = (f"{metric_label} is {shape}: the median is {format_value(med, unit)} "
                f"while the mean is {format_value(mean, unit)}.")
    bullets = [
        f"Half of all values fall between {format_value(q1, unit)} and "
        f"{format_value(q3, unit)} (IQR {format_value(iqr, unit)}).",
    ]
    if abs(skew) > 0.5:
        bullets.append(
            f"Because the distribution is {shape} (skew {skew:+.2f}), the mean is pulled "
            f"{'above' if skew > 0 else 'below'} the typical value - report the median "
            f"when describing a typical case."
        )
    if out:
        bullets.append(
            f"{out} value{'s' if out != 1 else ''} ({out / x.size * 100:.1f}%) fall outside "
            f"the Tukey fence [{format_value(lo, unit)}, {format_value(hi, unit)}]"
            + (" - expected for a naturally skewed business measure, so treat these as "
               "high-value cases rather than errors." if abs(skew) > 1 else "."))
    top_share = float(np.sort(x)[-max(1, x.size // 20):].sum() / x.sum() * 100) if x.sum() else 0
    if top_share > 20:
        bullets.append(f"The largest 5% of records account for {top_share:.1f}% of the total, "
                       f"so aggregate figures are sensitive to a handful of cases.")
    evidence = [Evidence(
        label=f"{metric_label} is {shape}", method="Fisher-Pearson skewness with Tukey fences",
        value=round(skew, 4), sample_size=int(x.size),
        comparison=f"median {med:,.2f}, mean {mean:,.2f}, IQR {iqr:,.2f}, {out} fence outliers.",
    )]
    return ChartNarrative(chart_id, title, headline, bullets, evidence)


def describe_correlation(
    chart_id: str,
    title: str,
    x: Sequence[float],
    y: Sequence[float],
    x_label: str,
    y_label: str,
) -> ChartNarrative:
    """Explain a scatter relationship - and refuse to imply causation."""
    pairs = [(float(a), float(b)) for a, b in zip(x, y)
             if a is not None and b is not None and np.isfinite(a) and np.isfinite(b)]
    if len(pairs) < 6:
        return ChartNarrative(chart_id, title, headline="Too few paired points to assess.")
    xs = [p[0] for p in pairs]
    ys = [p[1] for p in pairs]
    pear = pearson_correlation(xs, ys)
    spear = spearman_correlation(xs, ys)
    # TestResult.statistic holds the t-statistic; the correlation itself is the
    # effect size. Reading the wrong field yields nonsense like "r = +24".
    r = float(pear.effect_size if pear.effect_size is not None else float("nan"))
    rho = float(spear.effect_size if spear.effect_size is not None else float("nan"))
    if not np.isfinite(r):
        return ChartNarrative(chart_id, title,
                              headline=f"{x_label} or {y_label} has no variation to compare.")
    strength = ("very strong" if abs(r) >= 0.8 else "strong" if abs(r) >= 0.6 else
                "moderate" if abs(r) >= 0.4 else "weak" if abs(r) >= 0.2 else "negligible")
    direction = "positive" if r > 0 else "negative"
    headline = (f"{x_label} and {y_label} show a {strength} {direction} relationship "
                f"(r = {r:+.2f}, n = {len(pairs)})."
                if pear.significant else
                f"{x_label} and {y_label} show no statistically reliable relationship "
                f"(r = {r:+.2f}, p = {pear.p_value:.3g}).")
    bullets = [
        f"{y_label} varies with {x_label} to the extent of r-squared = {r * r:.2f}, meaning "
        f"{r * r * 100:.0f}% of the variation in {y_label} moves together with {x_label}.",
        f"Spearman rank correlation is {rho:+.2f}"
        + (", close to Pearson, so the relationship is broadly linear."
           if abs(rho - r) < 0.15 else
           ", noticeably different from Pearson, so the relationship is monotonic but "
           "not linear - a few extreme points may be doing the work."),
        "Correlation is not causation: this pairing is a starting point for a controlled "
        "comparison, not evidence that one drives the other.",
    ]
    evidence = [Evidence(
        label=f"{x_label} and {y_label} are {strength}ly correlated",
        method="Pearson correlation with t-approximation", value=round(r, 4),
        p_value=round(float(pear.p_value), 6), sample_size=len(pairs),
        comparison=f"Spearman rho {rho:+.4f}.",
    )]
    return ChartNarrative(chart_id, title, headline, bullets, evidence)
